'use client';

import { useCallback, useEffect, useRef, useState } from 'react';

import { api } from '@/lib/api';
import type { CaptchaConfig } from '@/types';

declare global {
  interface Window {
    grecaptcha?: {
      render: (container: HTMLElement, options: { sitekey: string; callback?: (token: string) => void }) => number;
      reset: (id?: number) => void;
      getResponse: (id?: number) => string;
    };
  }
}

/** The values a protected form must submit alongside its own fields. */
export type CaptchaAnswer = {
  captcha?: string;
  captcha_secret?: string;
  'g-recaptcha-response'?: string;
};

/**
 * Fetch the active challenge directly.
 *
 * The storefront already has it in site settings and should pass that through;
 * this is for the admin panel, which does not load storefront settings.
 */
export function useCaptchaConfig(): CaptchaConfig | null {
  const [config, setConfig] = useState<CaptchaConfig | null>(null);

  useEffect(() => {
    let cancelled = false;

    api<{ captcha: CaptchaConfig }>('/captcha')
      .then((data) => {
        if (!cancelled) setConfig(data.captcha);
      })
      .catch(() => undefined);

    return () => {
      cancelled = true;
    };
  }, []);

  return config;
}

/**
 * Renders whichever captcha challenges an administrator has switched on.
 *
 * Both are optional and independent, matching the source system: Google
 * reCAPTCHA v2 and/or a self-hosted six-digit code. When neither is enabled
 * this renders nothing and `answer()` returns an empty object, so the forms
 * that use it need no conditional logic of their own.
 */
export function useCaptcha(config: CaptchaConfig | null | undefined) {
  const [custom, setCustom] = useState(config?.custom ?? null);
  const [typed, setTyped] = useState('');
  const recaptchaRef = useRef<HTMLDivElement | null>(null);
  const widgetId = useRef<number | null>(null);

  useEffect(() => {
    setCustom(config?.custom ?? null);
  }, [config?.custom]);

  /** Fetch a new six-digit challenge. */
  const reload = useCallback(async () => {
    try {
      const data = await api<{ captcha: CaptchaConfig }>('/captcha');
      setCustom(data.captcha.custom);
      setTyped('');
    } catch {
      // Leave the current challenge in place; the visitor can retry.
    }
  }, []);

  // Google's script is only loaded when reCAPTCHA is actually enabled, so a
  // site that does not use it never talks to Google at all.
  const siteKey = config?.recaptcha?.site_key;

  useEffect(() => {
    if (!siteKey) return;

    const render = () => {
      if (!recaptchaRef.current || widgetId.current !== null || !window.grecaptcha) return;
      widgetId.current = window.grecaptcha.render(recaptchaRef.current, { sitekey: siteKey });
    };

    if (window.grecaptcha) {
      render();
      return;
    }

    const existing = document.getElementById('recaptcha-script');

    if (existing) {
      existing.addEventListener('load', render);
      return () => existing.removeEventListener('load', render);
    }

    const script = document.createElement('script');
    script.id = 'recaptcha-script';
    script.src = 'https://www.google.com/recaptcha/api.js?render=explicit';
    script.async = true;
    script.defer = true;
    script.addEventListener('load', render);
    document.head.appendChild(script);

    return () => script.removeEventListener('load', render);
  }, [siteKey]);

  /** The fields to merge into the request body. */
  const answer = useCallback((): CaptchaAnswer => {
    const payload: CaptchaAnswer = {};

    if (custom) {
      payload.captcha = typed;
      payload.captcha_secret = custom.secret;
    }

    if (siteKey && window.grecaptcha) {
      payload['g-recaptcha-response'] = window.grecaptcha.getResponse(widgetId.current ?? undefined);
    }

    return payload;
  }, [custom, typed, siteKey]);

  /** Call after a failed submit so the visitor gets a fresh challenge. */
  const reset = useCallback(() => {
    if (custom) void reload();
    if (siteKey && window.grecaptcha) window.grecaptcha.reset(widgetId.current ?? undefined);
  }, [custom, reload, siteKey]);

  const field =
    custom || siteKey ? (
      <div className="captcha-field">
        {custom && (
          <div className="form-group">
            <label className="form--label">Enter the code</label>
            <div className="captcha-field__challenge">
              <div
                className="captcha-field__image"
                // The SVG is generated by our own API from a fixed template —
                // no user input reaches it.
                dangerouslySetInnerHTML={{ __html: custom.svg }}
              />
              <button
                className="captcha-field__reload"
                type="button"
                onClick={() => void reload()}
                aria-label="Get a new code"
              >
                <i className="las la-redo-alt" />
              </button>
            </div>
            <input
              className="form-control form--control mt-2"
              type="text"
              inputMode="numeric"
              autoComplete="off"
              maxLength={6}
              placeholder="6-digit code"
              value={typed}
              onChange={(event) => setTyped(event.target.value)}
              required
            />
          </div>
        )}
        {siteKey && <div className="form-group" ref={recaptchaRef} />}
      </div>
    ) : null;

  return { field, answer, reset };
}
